name: Frontend Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        working-directory: frontend  # Set working directory to 'frontend'
        run: npm install

      - name: Run Tests
        working-directory: frontend  # Set working directory to 'frontend'
        run: npm test
